# Generated by Django 4.2.2 on 2023-06-16 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.CharField(max_length=50, null=True, verbose_name='Imágen')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('descripcion', models.CharField(max_length=230, verbose_name='Descripción')),
                ('enlace', models.URLField(max_length=255, verbose_name='Enlace')),
            ],
            options={
                'verbose_name': 'Certificaciones',
                'verbose_name_plural': 'Certificaciones',
            },
        ),
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descHabilidad', models.CharField(max_length=100, verbose_name='Habilidad')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
            },
        ),
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.CharField(max_length=50, null=True, verbose_name='Imágen')),
                ('texto_largo', models.TextField(max_length=2000, verbose_name='Texto Largo')),
            ],
            options={
                'verbose_name': 'Portafolio',
                'verbose_name_plural': 'Portafolio',
            },
        ),
    ]
