# Generated by Django 4.2.2 on 2023-06-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, null=True, verbose_name='Título')),
                ('descripcion', models.CharField(max_length=230, null=True, verbose_name='Descripción')),
                ('imagen', models.CharField(max_length=50, null=True, verbose_name='Imágen')),
                ('enlace', models.URLField(max_length=255, null=True, verbose_name='Enlace')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
    ]
