# Generated by Django 4.2.2 on 2023-06-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_proyectos'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='texto_enlace',
            field=models.CharField(max_length=50, null=True, verbose_name='Texto del Enlace'),
        ),
    ]
