# Generated by Django 4.2.2 on 2023-06-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_proyectos_texto_enlace'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='alt_imagen',
            field=models.URLField(max_length=255, null=True, verbose_name='Alt Imagen'),
        ),
    ]
